---
name: Release

on:
  push:
    tags:
      - "*"

  workflow_dispatch:
    inputs:
      VSC_NAME:
        required: true
        type: string

jobs:
  Release:
    uses: dennykorsukewitz/dennykorsukewitz/.github/workflows/reusable.release.vscode.yml@dev
    with:
      VSC_NAME: ${{ inputs.VSC_NAME || 'QuoteWithMarker' }}
    secrets:
      PAT: ${{ secrets.PAT }}
      VSC_PAT: ${{ secrets.VSC_PAT }}
